# Generated by Django 3.2.7 on 2021-09-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('numero_projetos', models.IntegerField(default=0)),
                ('numero_funcionarios', models.IntegerField(default=0)),
            ],
        ),
    ]
