# Generated by Django 3.2.7 on 2021-09-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('horas_supervisao', models.IntegerField()),
                ('horas_necessarias_para_conclusao', models.IntegerField()),
                ('prazo_estimado', models.DateField(default=None)),
                ('horas_trabalhadas_por_semana', models.IntegerField(default=0)),
                ('horas_realizadas', models.IntegerField()),
                ('data_ultimo_calculo_prazo', models.DateField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
    ]
